#!/bin/sh
chown -R root:root .
chmod 777 /tmp/
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs devtmpfs /dev
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console
insmod /rootme.ko
chown root:root /root/flag
chmod 400 /root/flag
chmod 666 /proc/rootme
chmod 700 /root/
setsid cttyhack setuidgid 1000 /bin/sh

umount /proc
umount /sys
poweroff -d 0  -f
