version: "3.1"
services:
  intro_pwn_1:
    container_name: intro_pwn_1
    build: pwn1/
    ports:
      - '9100:1024'
    stdin_open: true
    tty: true
    restart: always
    entrypoint: ./ynetd
    command: ./pwn1
  
  intro_pwn_2:
    container_name: intro_pwn_2
    build: pwn2/
    ports:
      - '9101:1024'
    stdin_open: true
    tty: true
    restart: always
    entrypoint: ./ynetd
    command: ./pwn2

  intro_pwn_3:
    container_name: intro_pwn_3
    build: pwn3/
    ports:
      - '9102:1024'
    stdin_open: true
    tty: true
    restart: always
    entrypoint: ./ynetd
    command: ./pwn3